### ISSUE TITLE
Update CI to use GitHub releases to push to NuGet

### ISSUE THREAD

**Issue by mauroservienti** [mauroservienti/code-repo-template#91]
```yml
on:
  release:
    types: [created]

jobs:
  release-job:
    name: Releasing
    if: github.event_name == 'release' && github.event.action == 'created'
# Push to NuGet instead of Feedz.io
```
